kakeibo/urls.py
from django.urls import path
from . import views

app_name = 'kakeibo'

urlpatterns = [

    path('expenditure_category/', views.ExpenditureCategoryIndexView.as_view(), name='expenditure_category_index'), 
    path('expenditure_category/create/', views.ExpenditureCategoryCreateView.as_view(), name='expenditure_category_create'), 
    path('expenditure_category/<int:pk>/update/', views.ExpenditureCategoryUpdateView.as_view(), name='expenditure_category_update'), 
    path('expenditure_category/<int:pk>/delete/', views.ExpenditureCategoryDeleteView.as_view(), name='expenditure_category_delete'), 

    path('expenditure/', views.ExpenditureIndexView.as_view(), name='expenditure_index'), 
    path('expenditure/chart/', views.ExpenditureChartView.as_view(), name='expenditure_chart'), 
    path('expenditure/create/', views.ExpenditureCreateView.as_view(), name='expenditure_create'), 
    path('expenditure/<int:pk>/update/', views.ExpenditureUpdateView.as_view(), name='expenditure_update'), 
    path('expenditure/<int:pk>/delete/', views.ExpenditureDeleteView.as_view(), name='expenditure_delete'), 
    path('expenditure/import/', views.ExpenditureImportView.as_view(), name='expenditure_import'),

    path('income_category/', views.IncomeCategoryIndexView.as_view(), name='income_category_index'), 
    path('income_category/create/', views.IncomeCategoryCreateView.as_view(), name='income_category_create'), 
    path('income_category/<int:pk>/update/', views.IncomeCategoryUpdateView.as_view(), name='income_category_update'), 
    path('income_category/<int:pk>/delete/', views.IncomeCategoryDeleteView.as_view(), name='income_category_delete'), 

    path('income/', views.IncomeIndexView.as_view(), name='income_index'), 
    path('income/create/', views.IncomeCreateView.as_view(), name='income_create'), 
    path('income/<int:pk>/update/', views.IncomeUpdateView.as_view(), name='income_update'), 
    path('income/<int:pk>/delete/', views.IncomeDeleteView.as_view(), name='income_delete'), 
    path('income/import/', views.IncomeImportView.as_view(), name='income_import'),
    path('income/export/', views.IncomeExportView, name='income_export'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('kakeibo/', include('kakeibo.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kakeibo/models.py
from django.db import models


class ExpenditureCategory(models.Model):
    number = models.IntegerField('カテゴリNo')
    name = models.CharField('カテゴリ名', max_length=20)

    def __str__(self):
        return self.name


class Expenditure(models.Model):
    category = models.ForeignKey(ExpenditureCategory, on_delete=models.PROTECT, verbose_name='カテゴリ')
    date = models.DateField('日付')
    price = models.IntegerField('金額')
    description = models.TextField('備考', null=True, blank=True, max_length=100)

    def __str__(self):
        return self.date.strftime('%Y-%m-%d')
    

class IncomeCategory(models.Model):
    number = models.IntegerField('カテゴリNo')
    name = models.CharField('カテゴリ名', max_length=20)

    def __str__(self):
        return self.name


class Income(models.Model):
    category = models.ForeignKey(IncomeCategory, on_delete=models.PROTECT, verbose_name='カテゴリ')
    date = models.DateField('日付')
    price = models.IntegerField('金額')
    description = models.TextField('備考', null=True, blank=True, max_length=100)

    def __str__(self):
        return self.date.strftime('%Y-%m-%d')

kakeibo/forms.py
from django import forms
from .models import ExpenditureCategory, Expenditure, IncomeCategory, Income
from django.conf import settings
from django.core.mail import EmailMessage
from django.utils import timezone


# ↓↓↓ --------------------　ExpenditureCategory_Form　-------------------- ↓↓↓

class ExpenditureCategoryForm(forms.ModelForm):
    class Meta:
        model = ExpenditureCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        for field in self.base_fields.values():
            field.widget.attrs['class'] = 'form-control'
        super().__init__(*args, **kwargs)

# ↑↑↑ --------------------　ExpenditureCategory_Form　-------------------- ↑↑↑

# ↓↓↓ --------------------　Expenditure_Form　-------------------- ↓↓↓

class ExpenditureSearchForm(forms.Form):
    start_year = 2024
    end_year = timezone.now().year + 1
    years = [(year, f'{year}年') for year in reversed(range(start_year, end_year + 1))]
    years.insert(0, (0, ''))
    YEAR_CHOICES = tuple(years)

    months = [(month, f'{month}月') for month in range(1, 13)]
    months.insert(0, (0, ''))
    MONTH_CHOICES = tuple(months)

    year = forms.ChoiceField(
        label='年',
        required=False,
        choices=YEAR_CHOICES,
        widget=forms.Select(attrs={'class': 'form'})
    )

    month = forms.ChoiceField(
        label='月',
        required=False,
        choices=MONTH_CHOICES,
        widget=forms.Select(attrs={'class': 'form'})
    )

    category = forms.ModelChoiceField(
        label='カテゴリ',
        required=False,
        queryset=ExpenditureCategory.objects.order_by('name'),
        widget=forms.Select(attrs={'class': 'form'})
    )

    key_word = forms.CharField(
        label='備考',
        required=False,
        widget=forms.TextInput(attrs={
            'autocomplete': 'off',
            'placeholder': '空白区切りで複数のキーワード入力可'
        })
    )


class ExpenditureForm(forms.ModelForm):
    class Meta:
        model = Expenditure
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        for field in self.base_fields.values():
            field.widget.attrs['class'] = 'form-control'
        super().__init__(*args, **kwargs)

# ↑↑↑ --------------------　Expenditure_Form　-------------------- ↑↑↑

# ↓↓↓ --------------------　IncomeCategory_Form　-------------------- ↓↓↓

class IncomeCategoryForm(forms.ModelForm):
    class Meta:
        model = IncomeCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        for field in self.base_fields.values():
            field.widget.attrs['class'] = 'form-control'
        super().__init__(*args, **kwargs)

# ↑↑↑ --------------------　IncomeCategory_Form　-------------------- ↑↑↑

# ↓↓↓ --------------------　Income_Form　-------------------- ↓↓↓

class IncomeForm(forms.ModelForm):
    class Meta:
        model = Income
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        for field in self.base_fields.values():
            field.widget.attrs['class'] = 'form-control'
        super().__init__(*args, **kwargs)

# ↑↑↑ --------------------　Income_Form　-------------------- ↑↑↑

# ↓↓↓ --------------------　CSVUpload_Form　-------------------- ↓↓↓

class CsvUploadForm(forms.Form):
    file = forms.FileField(label='CSVファイル')

# ↑↑↑ --------------------　CSVUpload_Form　-------------------- ↑↑↑

kakeibo/views.py
import io
import pandas as pd
import numpy as np
from django.views import generic
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from .models import ExpenditureCategory, Expenditure, IncomeCategory, Income
from .forms import ExpenditureCategoryForm, ExpenditureSearchForm, ExpenditureForm, IncomeCategoryForm, IncomeForm
from .forms import CsvUploadForm
from . import function
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django_pandas.io import read_frame
from django.core import paginator
from django.contrib import messages
from urllib.parse import urlencode
from django.contrib.auth import get_user_model
User = get_user_model()


# ↓↓↓ --------------------　ExpenditureCategory　-------------------- ↓↓↓

class ExpenditureCategoryIndexView(LoginRequiredMixin, generic.ListView):
    model = ExpenditureCategory
    template_name = 'kakeibo/expenditure_category_index.html'


class ExpenditureCategoryCreateView(LoginRequiredMixin, generic.CreateView):
    form_class = ExpenditureCategoryForm
    template_name = 'kakeibo/expenditure_category_create.html'
    success_url = reverse_lazy('kakeibo:expenditure_category_index')


class ExpenditureCategoryUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = ExpenditureCategory
    form_class = ExpenditureCategoryForm
    template_name = 'kakeibo/expenditure_category_update.html'
    success_url = reverse_lazy('kakeibo:expenditure_category_index')


class ExpenditureCategoryDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = ExpenditureCategory
    template_name = 'kakeibo/expenditure_category_delete.html'
    success_url = reverse_lazy('kakeibo:expenditure_category_index')
    
# ↑↑↑ --------------------　ExpenditureCategory　-------------------- ↑↑↑

# ↓↓↓ --------------------　Expenditure　-------------------- ↓↓↓

def queryset_filter1(year, month, *, category=None, key_word=None):
    queryset = Expenditure.objects.all().order_by('date')

    if category:
        queryset = queryset.filter(category=category)

    if year and year != '0':
        queryset = queryset.filter(date__year=year)

    if month and month != '0':
        queryset = queryset.filter(date__month=month)

    if key_word:
        if key_word:
            for word in key_word.split():
                queryset = queryset.filter(description__icontains=word)

    return queryset

paginate_number = 10


class ExpenditureIndexView(LoginRequiredMixin, generic.FormView):
    template_name = 'kakeibo/expenditure_index.html'
    form_class = ExpenditureSearchForm
    success_url = reverse_lazy('kakeibo:expenditure_index')

    def form_valid(self, form):
        category = form.cleaned_data.get('category')
        year = form.cleaned_data.get('year')
        month = form.cleaned_data.get('month')
        key_word = form.cleaned_data.get('key_word')

        queryset = queryset_filter1(year, month, category=category, key_word=key_word)

        if 'search' in self.request.POST:
            if category:
                filter_word = urlencode({'category': category.pk, 'year': year, 'month': month, 'key_word': key_word})
            else:
                filter_word = urlencode({'year': year, 'month': month, 'key_word': key_word})

            return redirect(reverse('kakeibo:expenditure_index') + '?page=1&' + filter_word)
        
        elif 'export' in self.request.POST:
            response = HttpResponse(content_type='text/csv; charset=Shift-JIS')
            response['Content-Disposition'] = 'filename="Expenditure.csv"'
            df = read_frame(queryset)
            df.to_csv(response, sep=',', index=False, encoding='utf-8')
            return response


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        category = self.request.GET.get('category')
        year = self.request.GET.get('year')
        month = self.request.GET.get('month')
        key_word = self.request.GET.get('key_word')
        queryset = queryset_filter1(year, month, category=category, key_word=key_word)

        paginated_by = paginate_number
        my_paginator = paginator.Paginator(queryset, paginated_by)

        page = self.request.GET.get('page')
        try:
            page_obj = my_paginator.page(page)
        except (paginator.PageNotAnInteger, paginator.EmptyPage):
            page_obj = my_paginator.page(1)

        context['page_obj'] = page_obj
        context['expenditure_list'] = page_obj.object_list

        if '&' in self.request.GET.urlencode():
            filter_word = self.request.GET.urlencode()
            filter_word = filter_word[filter_word.index('&'):]
            context['filter_word'] = filter_word

        return context

        
class ExpenditureChartView(generic.ListView):
    model = Expenditure
    template_name = 'kakeibo/expenditure_chart.html'

    def get_queryset(self):
        queryset =  super().get_queryset()
        self.form = form = ExpenditureSearchForm(self.request.GET or None)

        if form.is_valid():
            year = form.cleaned_data.get('year')
            month = form.cleaned_data.get('month')
            queryset = queryset_filter1(year, month)

        return queryset
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.form = form = ExpenditureSearchForm(self.request.GET or None)
        context['form'] = self.form

        queryset = self.get_queryset()

        df = read_frame(queryset)

        total_expenditure_price = sum([row.price for row in df.itertuples()])
        context['total_expenditure_price'] = total_expenditure_price

        df['month'] = pd.to_datetime(df['date']).dt.strftime('%y-%m')
        df_chart1 = pd.pivot_table(df, index='month', values='price', aggfunc=np.sum)
        df_chart1 = df_chart1.sort_values('month')

        x = [row[0] for row in df_chart1.itertuples()]
        y = [row.price for row in df_chart1.itertuples()]
        chart1 = function.create_barchart(x, y)
        context['chart1'] = chart1


        df_chart2 = pd.pivot_table(df, index='category', values='price', aggfunc=np.sum)

        totals_for_each_category = [
            [row[0], row.price, f'{(row.price / total_expenditure_price)*100:.2f}%', ExpenditureCategory.objects.get(name=row[0]).number]
            for row in df_chart2.itertuples()]
        totals_for_each_category = sorted(totals_for_each_category, key=lambda x: x[3])

        category_list = [row[0] for row in totals_for_each_category]
        price_list = [row[1] for row in totals_for_each_category]
        chart2 = function.create_piechart(price_list, category_list)
        context['chart2'] = chart2
        
        context['totals_for_each_category'] = totals_for_each_category

        income_queryset = Income.objects.all().order_by('pk')
        if form.is_valid():
            year = form.cleaned_data.get('year')
            month = form.cleaned_data.get('month')

            if year and year != '0':
                income_queryset = income_queryset.filter(date__year=year)

            if month and month != '0':
                income_queryset = income_queryset.filter(date__month=month)

        df_income = read_frame(income_queryset)
        total_income_price = sum([row.price for row in df_income.itertuples()])
        context['total_income_price'] = total_income_price

        context['total_income_and_expenditure_price'] = total_income_price - total_expenditure_price

        return context


class ExpenditureCreateView(LoginRequiredMixin, generic.CreateView):
    form_class = ExpenditureForm
    template_name = 'kakeibo/expenditure_create.html'
    success_url = reverse_lazy('kakeibo:expenditure_index')
    

class ExpenditureUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Expenditure
    form_class = ExpenditureForm
    template_name = 'kakeibo/expenditure_update.html'
    success_url = reverse_lazy('kakeibo:expenditure_index')


class ExpenditureDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Expenditure
    template_name = 'kakeibo/expenditure_delete.html'
    success_url = reverse_lazy('kakeibo:expenditure_index')


class ExpenditureImportView(generic.FormView):
    template_name = 'kakeibo/expenditure_import.html'
    form_class = CsvUploadForm
    success_url = reverse_lazy('kakeibo:expenditure_index')

    def form_valid(self, form):
        cleaned_data_file = form.cleaned_data['file']
        df = pd.read_csv(io.TextIOWrapper(cleaned_data_file))

        saved_expenditure_object_exsist = None
        expenditure_objects_for_update = []
        expenditure_objects_for_create = []

        for row in df.itertuples():
            if len(Expenditure.objects.filter(pk=row.id).values()) >= 1:
                saved_expenditure_object_exsist = True
                expenditure = Expenditure.objects.get(pk=row.id)
            else:
                saved_expenditure_object_exsist = False
                expenditure = Expenditure(pk=row.id)
                
            expenditure.category = ExpenditureCategory.objects.get(name=row.category)
            expenditure.date = pd.to_datetime(row.date)
            expenditure.price = row.price
            expenditure.description = row.description
            
            if saved_expenditure_object_exsist:
                expenditure_objects_for_update.append(expenditure)
            else:
                expenditure_objects_for_create.append(expenditure)

        Expenditure.objects.bulk_update(expenditure_objects_for_update, fields=['category', 'date', 'price', 'description'])
        Expenditure.objects.bulk_create(expenditure_objects_for_create)

        return super().form_valid(form)

# ↑↑↑ --------------------　Expenditure　-------------------- ↑↑↑

# ↓↓↓ --------------------　IncomeCategory　-------------------- ↓↓↓

class IncomeCategoryIndexView(LoginRequiredMixin, generic.ListView):

templates/kakeibo/expenditure_category_create.html
{% extends 'base.html' %}

{% block headertitle %}
支出項目新規登録
{% endblock %}

{% block content %}
<h2>支出項目新規登録</h2>

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
    <button type="submit">登録</button>
    <button onclick="location.href='{% url 'kakeibo:expenditure_category_index' %}'">戻る</button>
</form>
{% endblock %}

templates/kakeibo/expenditure_category_delete.html
{% extends 'base.html' %}

{% block headertitle %}
支出項目削除
{% endblock %}

{% block content %}
<h1>支出項目削除</h1>
<h2>削除しますか？</h2>
<ul>
    <li>ナンバー：{{ expenditurecategory.number }}</li>
    <li>項目名：{{ expenditurecategory.name }}</li>
</ul>
<div class="d-flex flex-row mb-3">
    <div class="p-2">
        <form method="POST">
        {% csrf_token %}
            <button tytde="submit" class="btn btn-danger">削除</button>
        </form>
    </div>
    <div class="p-2">
        <button onclick="location.href='{% url 'kakeibo:expenditure_category_index' %}'" class="btn btn-primary">戻る</button>
    </div>
</div>
{% endblock %}

templates/kakeibo/expenditure_category_update.html
{% extends 'base.html' %}

{% block headertitle %}
支出項目編集
{% endblock %}

{% block content %}
<h2>支出項目編集</h2>

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
    <button type="submit">更新</button>
    <button onclick="location.href='{% url 'kakeibo:expenditure_index' %}'">戻る</button>
</form>
{% endblock %}

templates/kakeibo/expenditure_create.html
{% extends 'base.html' %}

{% block headertitle %}
支出新規登録
{% endblock %}

{% block content %}
<h2>支出新規登録</h2>

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
    <button type="submit">登録</button>
    <button onclick="location.href='{% url 'kakeibo:expenditure_index' %}'">戻る</button>
</form>
{% endblock %}

templates/kakeibo/expenditure_delete.html
{% extends 'base.html' %}

{% block headertitle %}
支出削除
{% endblock %}

{% block content %}
<h1>支出削除</h1>
<h2>削除しますか？</h2>
<ul>
    <li>カテゴリー：{{ expenditure.category }}</li>
    <li>日付：{{ expenditure.date }}</li>
    <li>金額：{{ expenditure.price }}</li>
    <li>備考：{{ expenditure.description }}</li>
</ul>
<div class="d-flex flex-row mb-3">
    <div class="p-2">
        <form method="POST">
        {% csrf_token %}
            <button tytde="submit" class="btn btn-danger">削除</button>
        </form>
    </div>
    <div class="p-2">
        <button onclick="location.href='{% url 'kakeibo:expenditure_index' %}'" class="btn btn-primary">戻る</button>
    </div>
</div>
{% endblock %}

templates/kakeibo/expenditure_import.html
{% extends 'base.html' %}

{% block headertitle %}
支出一覧CSVファイルインポート
{% endblock %}

{% block content %}
<h1>支出一覧CSVファイルインポート</h1>

<form action="" method="POST" enctype="multipart/form-data">
  <p>ファイルを選択ボタンをクリックして、アップロードするCSVファイルを選択してください</p>
  {% csrf_token %}
  <div class="form-group">
    {{form.file}}
  </div>
  <br/>
  <button type="submit">送信</button>
  <button onclick="location.href='{% url 'kakeibo:expenditure_index' %}'">戻る</button>
</form>
{% endblock %}

templates/kakeibo/income_category_create.html
{% extends 'base.html' %}

{% block headertitle %}
収入項目新規登録
{% endblock %}

{% block content %}
<h2>収入項目新規登録</h2>

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
    <button type="submit">登録</button>
    <button onclick="location.href='{% url 'kakeibo:income_category_index' %}'">戻る</button>
</form>
{% endblock %}

templates/kakeibo/income_category_delete.html
{% extends 'base.html' %}

{% block headertitle %}
収入項目削除
{% endblock %}

{% block content %}
<h1>収入項目削除</h1>
<h2>削除しますか？</h2>
<ul>
    <li>ナンバー：{{ incomecategory.number }}</li>
    <li>項目名：{{ incomecategory.name }}</li>
</ul>
<div class="d-flex flex-row mb-3">
    <div class="p-2">
        <form method="POST">
        {% csrf_token %}
            <button tytde="submit" class="btn btn-danger">削除</button>
        </form>
    </div>
    <div class="p-2">
        <button onclick="location.href='{% url 'kakeibo:income_category_index' %}'" class="btn btn-primary">戻る</button>
    </div>
</div>
{% endblock %}

templates/kakeibo/income_category_index.html
{% extends 'base.html' %}

{% block headertitle %}
収入項目一覧
{% endblock %}

{% block content %}
{% load humanize %}
<h3><a href="{% url 'kakeibo:income_category_index' %}">収入項目一覧</a></h3>

<div class="list">
  <table>
    <thead>
      <tr>
        <th>ナンバー</th>
        <th>項目名</th>
      </tr>
    </thead>
    <tbody>
      {% for income in incomecategory_list %}
      <tr>
        <td class="text-end">{{ income.number }}</td>
        <td class="text-end">{{ income.name }}</a></td>
        <td><a href="{% url 'kakeibo:income_category_update' income.pk %}">編集</a></td>
        <td><a href="{% url 'kakeibo:income_category_delete' income.pk %}">削除</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% include 'kakeibo/kakeibo_pagenation.html' %}
{% endblock %}

templates/kakeibo/income_create.html
{% extends 'base.html' %}

{% block headertitle %}
収入新規登録
{% endblock %}

{% block content %}
<h2>収入新規登録</h2>

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
    <button type="submit">登録</button>
    <button onclick="location.href='{% url 'kakeibo:income_index' %}'">戻る</button>
</form>
{% endblock %}

templates/kakeibo/income_delete.html
{% extends 'base.html' %}

{% block headertitle %}
収入削除
{% endblock %}

{% block content %}
<h1>収入削除</h1>
<h2>削除しますか？</h2>
<ul>
    <li>カテゴリー：{{ income.category }}</li>
    <li>日付：{{ income.date }}</li>
    <li>金額：{{ income.price }}</li>
    <li>備考：{{ income.description }}</li>
</ul>
<div class="d-flex flex-row mb-3">
    <div class="p-2">
        <form method="POST">
        {% csrf_token %}
            <button tytde="submit" class="btn btn-danger">削除</button>
        </form>
    </div>
    <div class="p-2">
        <button onclick="location.href='{% url 'kakeibo:income_index' %}'" class="btn btn-primary">戻る</button>
    </div>
</div>
{% endblock %}

templates/kakeibo/income_import.html
{% extends 'base.html' %}

{% block headertitle %}
収入一覧CSVファイルインポート
{% endblock %}

{% block content %}
<h1>収入一覧CSVファイルインポート</h1>

<form action="" method="POST" enctype="multipart/form-data">
  <p>ファイルを選択ボタンをクリックして、インポートするCSVファイルを選択してください</p>
  {% csrf_token %}
  <div class="form-group">
    {{form.file}}
  </div>
  <br/>
  <button type="submit">送信</button>
  <button onclick="location.href='{% url 'kakeibo:income_index' %}'">戻る</button>
</form>
{% endblock %}

templates/kakeibo/income_index.html
{% extends 'base.html' %}

{% block headertitle %}
収入一覧
{% endblock %}

{% block content %}
{% load humanize %}
<h3><a href="{% url 'kakeibo:income_index' %}">収入一覧</a></h3>

<div class="list">
  <table>
    <thead>
      <tr>
        <th>カテゴリー</th>
        <th>日付</th>
        <th>金額</th>
        <th>備考</th>
      </tr>
    </thead>
    <tbody>
      {% for income in income_list %}
      <tr>
        <td class="text-center">{{ income.category }}</td>
        <td class="text-center">{{ income.date }}</a></td>
        <td class="text-end">{{ income.price | intcomma }}</td>
        <td class="text-center">{{ income.description }}</td>
        <td><a href="{% url 'kakeibo:income_update' income.pk %}">編集</a></td>
        <td><a href="{% url 'kakeibo:income_delete' income.pk %}">削除</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<a href="{% url 'kakeibo:income_export' %}">収入一覧ダウンロード</a>
{% endblock %}

templates/kakeibo/income_update.html
{% extends 'base.html' %}

{% block headertitle %}
収入編集
{% endblock %}

{% block content %}
<h2>収入編集</h2>

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
    <button type="submit">更新</button>
    <button onclick="location.href='{% url 'kakeibo:income_index' %}'">戻る</button>
</form>
{% endblock %}