kakeibo/urls.py
from django.urls import path
from . import views

app_name = 'kakeibo'

urlpatterns = [

    path('expenditure_category/', views.ExpenditureCategoryIndexView.as_view(), name='expenditure_category_index'), 
    path('expenditure_category/create/', views.ExpenditureCategoryCreateView.as_view(), name='expenditure_category_create'), 
    path('expenditure_category/<int:pk>/update/', views.ExpenditureCategoryUpdateView.as_view(), name='expenditure_category_update'), 
    path('expenditure_category/<int:pk>/delete/', views.ExpenditureCategoryDeleteView.as_view(), name='expenditure_category_delete'), 

    path('expenditure/', views.ExpenditureIndexView.as_view(), name='expenditure_index'), 
    path('expenditure/chart/', views.ExpenditureChartView.as_view(), name='expenditure_chart'), 
    path('expenditure/create/', views.ExpenditureCreateView.as_view(), name='expenditure_create'), 
    path('expenditure/<int:pk>/update/', views.ExpenditureUpdateView.as_view(), name='expenditure_update'), 
    path('expenditure/<int:pk>/delete/', views.ExpenditureDeleteView.as_view(), name='expenditure_delete'), 
    path('expenditure/import/', views.ExpenditureImportView.as_view(), name='expenditure_import'),

    path('income_category/', views.IncomeCategoryIndexView.as_view(), name='income_category_index'), 
    path('income_category/create/', views.IncomeCategoryCreateView.as_view(), name='income_category_create'), 
    path('income_category/<int:pk>/update/', views.IncomeCategoryUpdateView.as_view(), name='income_category_update'), 
    path('income_category/<int:pk>/delete/', views.IncomeCategoryDeleteView.as_view(), name='income_category_delete'), 

    path('income/', views.IncomeIndexView.as_view(), name='income_index'), 
    path('income/create/', views.IncomeCreateView.as_view(), name='income_create'), 
    path('income/<int:pk>/update/', views.IncomeUpdateView.as_view(), name='income_update'), 
    path('income/<int:pk>/delete/', views.IncomeDeleteView.as_view(), name='income_delete'), 
    path('income/import/', views.IncomeImportView.as_view(), name='income_import'),
    path('income/export/', views.IncomeExportView, name='income_export'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('kakeibo/', include('kakeibo.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <title>{% block headertitle %}{% endblock %}</title>
    {% include 'css.html' %}
  </head>
  <body>
    <div class="container-nav">
      {% include 'nav.html' %}
    </div>
    <div class="container-body">
      <div class="container-main">
        <main>
          {% if messages %}
            <div>
              <ul>
                  {% for message in messages %}
                    <li class="base_message">{{ message | linebreaksbr }}</li>
                  {% endfor %}
              </ul>
            </div>
          {% endif %}
          {% block content %}{% endblock %}
        </div>
      </main>
    </div>
    {% include 'js.html' %}
  </body>
</html>

templates/css.html
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

templates/js.html
{% load static %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.min.js" integrity="sha512-CQBWl4fJHWbryGE+Pc7UAxWMUMNMWzWxF4SQo9CgkJIN1kx6djDQZjh3Y8SZ1d+6I+1zze6Z7kHXO7q3UyZAWw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="{% static 'javascript/style.js' %}"></script>

templates/nav.html
<nav class="navbar navbar-expand-lg bg-info">
  <div class="container-fluid">
    <a class="navbar-brand" href="">{{ user.email }}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse text-end" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'account_logout' %}">ログアウト</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            支出項目
          </a>
          <ul class="dropdown-menu text-end">
            <li><a class="dropdown-item" href="{% url 'kakeibo:expenditure_category_index' %}">一覧</a></li>
            <li><a class="dropdown-item" href="{% url 'kakeibo:expenditure_category_create' %}">新規登録</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            支出
          </a>
          <ul class="dropdown-menu text-end">
            <li><a class="dropdown-item" href="{% url 'kakeibo:expenditure_index' %}">一覧</a></li>
            <li><a class="dropdown-item" href="{% url 'kakeibo:expenditure_chart' %}">収支グラフ</a></li>
            <li><a class="dropdown-item" href="{% url 'kakeibo:expenditure_create' %}">新規登録</a></li>
            <li><a class="dropdown-item" href="{% url 'kakeibo:expenditure_import' %}">ファイルインポート</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown"></li>
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            収入項目
          </a>
          <ul class="dropdown-menu text-end">
            <li><a class="dropdown-item" href="{% url 'kakeibo:income_category_index' %}">一覧</a></li>
            <li><a class="dropdown-item" href="{% url 'kakeibo:income_category_create' %}">新規登録</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            収入
          </a>
          <ul class="dropdown-menu text-end">
            <li><a class="dropdown-item" href="{% url 'kakeibo:income_index' %}">一覧</a></li>
            <li><a class="dropdown-item" href="{% url 'kakeibo:income_create' %}">新規登録</a></li>
            <li><a class="dropdown-item" href="{% url 'kakeibo:income_import' %}">一覧CSVファイルインポート</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>